"""Password hashing — and proof the passlib->bcrypt switch is backward-compatible.

The critical guarantee: passwords hashed by the OLD passlib-based code must still
verify under the NEW direct-bcrypt code, so existing users can still log in after
the dependency change. LEGACY_HASH below was produced by the previous stack
(passlib 1.7.4 + bcrypt 3.2.2) for the password "password123".
"""

from auth import verify_password, get_password_hash

# Real hash generated by the previous passlib/bcrypt implementation.
LEGACY_HASH = "$2b$12$iv9dne/ymS8DQfJCj1zu.uy4n/I2fTwJv8BszWVBTaP6IdU8J34Ua"


def test_legacy_passlib_hash_still_verifies():
    assert verify_password("password123", LEGACY_HASH) is True
    assert verify_password("wrong-password", LEGACY_HASH) is False


def test_hash_roundtrip():
    hashed = get_password_hash("hunter2")
    assert hashed.startswith("$2b$")
    assert verify_password("hunter2", hashed) is True
    assert verify_password("nope", hashed) is False


def test_hashes_are_salted():
    # Same password, different salts -> different hashes.
    assert get_password_hash("same") != get_password_hash("same")


def test_unicode_password_roundtrip():
    pw = "pâsswörd-éàü"  # accented chars are multi-byte in UTF-8
    hashed = get_password_hash(pw)
    assert verify_password(pw, hashed) is True
